/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Swimming;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.security.CodeSource;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;

/**
 *
 * @author tasos
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() { 
    //          this.setIconImage(Toolkit.getDefaultToolkit().getImage("E:\\Users\\tasos\\Documents\\NetBeansProjects\\Michael Phelps\\icon.jpg"));
   //     frame.setIconImage();
        setIcon();     
        
        initComponents();
 //       JFrame.setIconImage(new ImageIcon(getClass().getClassLoader().getResource(null)));
    }
    
    private void setIcon(){
    //    this.setIconImage(Toolkit.getDefaultToolkit().getImage("src/Swimming/MichaelPhelps.png"));
        this.setIconImage(createImage("/Swimming/Michaelicon.jpg").getImage());

    }
    
    private ImageIcon createImage(String path){
        return new ImageIcon(java.awt.Toolkit.getDefaultToolkit().getClass().getResource(path));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPanelProgram = new javax.swing.JTabbedPane();
        jPanelHome_New = new javax.swing.JPanel();
        jButtonDownload = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabelMeters = new javax.swing.JLabel();
        jButtonFinish = new javax.swing.JButton();
        jButtonAddNew = new javax.swing.JButton();
        jLabelStyle = new javax.swing.JLabel();
        jTextFieldSpecificStyle = new javax.swing.JTextField();
        textFieldMeters = new java.awt.TextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaProgram = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jPanelHome_Old = new javax.swing.JPanel();
        jLabelButterfly = new javax.swing.JLabel();
        textFieldButterfly = new java.awt.TextField();
        jLabelBackstroke = new javax.swing.JLabel();
        textFieldBackstroke = new java.awt.TextField();
        jLabelBreaststroke = new javax.swing.JLabel();
        textFieldBreakstroke = new java.awt.TextField();
        jLabelFreestyle = new javax.swing.JLabel();
        textFieldFreestyle = new java.awt.TextField();
        jButtonPrint = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabelImage = new javax.swing.JLabel();
        jTabbedPane2Tips = new javax.swing.JTabbedPane();
        jPanelWeeklyProgram = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelPoolSize = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelPoolSize1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanelCalendar = new javax.swing.JPanel();
        jPanelGallery = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelWarning = new javax.swing.JLabel();
        jLabelTrainProgram = new javax.swing.JLabel();
        jLabelFinalButterflyMeters = new javax.swing.JLabel();
        jLabelFinalBackstrokeMeters = new javax.swing.JLabel();
        jLabelFinalBreakstrokeMeters = new javax.swing.JLabel();
        jLabelFinalFreestyleMeters = new javax.swing.JLabel();
        jButtonScreenShot = new javax.swing.JButton();
        jLabelDateForProgram = new javax.swing.JLabel();
        jFileChooser = new javax.swing.JFileChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swimming/m12.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Michael Phelps");
        setBackground(new java.awt.Color(51, 102, 255));
        setName("Swimming App"); // NOI18N
        setResizable(false);

        jTabbedPanelProgram.setBackground(new java.awt.Color(0, 168, 240));
        jTabbedPanelProgram.setBorder(new javax.swing.border.MatteBorder(null));
        jTabbedPanelProgram.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanelHome_New.setLayout(null);

        jButtonDownload.setText("Download");
        jButtonDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDownloadActionPerformed(evt);
            }
        });
        jPanelHome_New.add(jButtonDownload);
        jButtonDownload.setBounds(371, 416, 110, 23);
        jButtonDownload.setVisible(false);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Φτιάξε το δικό σου πρόγραμμα κολύμβησης προσθέτοντας τα μέτρα κάθε άσκησης κολύμβησης που θέλετε να κάνει ο αθλητής σας !");
        jPanelHome_New.add(jLabel19);
        jLabel19.setBounds(10, 11, 824, 15);

        jLabelMeters.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelMeters.setText("Μέτρα(m) :");
        jPanelHome_New.add(jLabelMeters);
        jLabelMeters.setBounds(10, 54, 78, 17);

        jButtonFinish.setText("Finish Program");
        jButtonFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinishActionPerformed(evt);
            }
        });
        jPanelHome_New.add(jButtonFinish);
        jButtonFinish.setBounds(10, 126, 130, 23);

        jButtonAddNew.setText("Add New");
        jButtonAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddNewActionPerformed(evt);
            }
        });
        jPanelHome_New.add(jButtonAddNew);
        jButtonAddNew.setBounds(10, 92, 130, 23);

        jLabelStyle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelStyle.setText("Στυλ/Λεπτομέρεις :");
        jPanelHome_New.add(jLabelStyle);
        jLabelStyle.setBounds(186, 54, 134, 17);

        jTextFieldSpecificStyle.setBackground(new java.awt.Color(1, 174, 234));
        jTextFieldSpecificStyle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanelHome_New.add(jTextFieldSpecificStyle);
        jTextFieldSpecificStyle.setBounds(330, 44, 290, 30);

        textFieldMeters.setBackground(new java.awt.Color(1, 174, 234));
        textFieldMeters.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        textFieldMeters.setForeground(new java.awt.Color(255, 255, 255));
        textFieldMeters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldMetersActionPerformed(evt);
            }
        });
        textFieldMeters.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldMetersKeyTyped(evt);
            }
        });
        jPanelHome_New.add(textFieldMeters);
        textFieldMeters.setBounds(100, 50, 70, 20);

        jTextAreaProgram.setEditable(false);
        jTextAreaProgram.setBackground(new java.awt.Color(240, 240, 240));
        jTextAreaProgram.setColumns(20);
        jTextAreaProgram.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextAreaProgram.setRows(5);
        jScrollPane2.setViewportView(jTextAreaProgram);
        jTextAreaProgram.setVisible(false);

        jTextAreaProgram.setBackground(new Color(0,0,0,64));

        DateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");
        Date date = new Date();

        jTextAreaProgram.setText("Πρόγραμμα" + "  -  " + dateFormat.format(date));

        jPanelHome_New.add(jScrollPane2);
        jScrollPane2.setBounds(202, 92, 440, 318);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swimming/m12.jpg"))); // NOI18N
        jLabel21.setText("jLabel21");
        jPanelHome_New.add(jLabel21);
        jLabel21.setBounds(0, 0, 870, 450);

        jTabbedPanelProgram.addTab("Home", jPanelHome_New);

        jPanelHome_Old.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanelHome_Old.setPreferredSize(new java.awt.Dimension(1034, 374));
        jPanelHome_Old.setLayout(null);

        jLabelButterfly.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelButterfly.setText("Butterfly");
        jPanelHome_Old.add(jLabelButterfly);
        jLabelButterfly.setBounds(10, 370, 55, 15);
        jLabelButterfly.getAccessibleContext().setAccessibleName("jLabelButterfly");

        textFieldButterfly.setBackground(new java.awt.Color(1, 174, 234));
        textFieldButterfly.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        textFieldButterfly.setForeground(new java.awt.Color(255, 255, 255));
        textFieldButterfly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldButterflyActionPerformed(evt);
            }
        });
        textFieldButterfly.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldButterflyKeyTyped(evt);
            }
        });
        jPanelHome_Old.add(textFieldButterfly);
        textFieldButterfly.setBounds(100, 370, 70, 20);

        jLabelBackstroke.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelBackstroke.setText("Backstroke");
        jPanelHome_Old.add(jLabelBackstroke);
        jLabelBackstroke.setBounds(180, 370, 67, 20);

        textFieldBackstroke.setBackground(new java.awt.Color(1, 174, 234));
        textFieldBackstroke.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        textFieldBackstroke.setForeground(new java.awt.Color(255, 255, 255));
        textFieldBackstroke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldBackstrokeActionPerformed(evt);
            }
        });
        textFieldBackstroke.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldBackstrokeKeyTyped(evt);
            }
        });
        jPanelHome_Old.add(textFieldBackstroke);
        textFieldBackstroke.setBounds(250, 370, 70, 20);

        jLabelBreaststroke.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelBreaststroke.setText("Breaststroke");
        jPanelHome_Old.add(jLabelBreaststroke);
        jLabelBreaststroke.setBounds(10, 400, 78, 15);

        textFieldBreakstroke.setBackground(new java.awt.Color(1, 174, 234));
        textFieldBreakstroke.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        textFieldBreakstroke.setForeground(new java.awt.Color(255, 255, 255));
        textFieldBreakstroke.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldBreakstrokeKeyTyped(evt);
            }
        });
        jPanelHome_Old.add(textFieldBreakstroke);
        textFieldBreakstroke.setBounds(100, 400, 70, 20);

        jLabelFreestyle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelFreestyle.setText("Freestyle ");
        jPanelHome_Old.add(jLabelFreestyle);
        jLabelFreestyle.setBounds(180, 400, 58, 15);

        textFieldFreestyle.setBackground(new java.awt.Color(1, 174, 234));
        textFieldFreestyle.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        textFieldFreestyle.setForeground(new java.awt.Color(255, 255, 255));
        textFieldFreestyle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldFreestyleKeyTyped(evt);
            }
        });
        jPanelHome_Old.add(textFieldFreestyle);
        textFieldFreestyle.setBounds(250, 400, 70, 20);

        jButtonPrint.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonPrint.setText("Print");
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });
        jPanelHome_Old.add(jButtonPrint);
        jButtonPrint.setBounds(770, 420, 84, 23);
        jButtonPrint.setVisible(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel7.setText("* Επέλεξε τα μέτρα για κάθε στυλ");
        jLabel7.setEnabled(true);
        jPanelHome_Old.add(jLabel7);
        jLabel7.setBounds(10, 430, 190, 13);

        jLabelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swimming/m12.jpg"))); // NOI18N
        jPanelHome_Old.add(jLabelImage);
        jLabelImage.setBounds(0, 0, 870, 450);

        jTabbedPanelProgram.addTab("Home(Old)", jPanelHome_Old);

        jTabbedPane2Tips.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swimming/pp.PNG"))); // NOI18N

        jLabelPoolSize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPoolSize.setText("Pool Size : 25 m ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Πανελλήνιος ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Κολυμβητήριο Πεύκη");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swimming/progr.PNG"))); // NOI18N

        jLabelPoolSize1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPoolSize1.setText("Pool Size : 25 m ");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOpaque(true);

        javax.swing.GroupLayout jPanelWeeklyProgramLayout = new javax.swing.GroupLayout(jPanelWeeklyProgram);
        jPanelWeeklyProgram.setLayout(jPanelWeeklyProgramLayout);
        jPanelWeeklyProgramLayout.setHorizontalGroup(
            jPanelWeeklyProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWeeklyProgramLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelWeeklyProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWeeklyProgramLayout.createSequentialGroup()
                        .addComponent(jLabelPoolSize)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelWeeklyProgramLayout.createSequentialGroup()
                        .addGroup(jPanelWeeklyProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabelPoolSize1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanelWeeklyProgramLayout.createSequentialGroup()
                .addGroup(jPanelWeeklyProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanelWeeklyProgramLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)))
                .addGap(0, 167, Short.MAX_VALUE))
            .addComponent(jSeparator2)
        );
        jPanelWeeklyProgramLayout.setVerticalGroup(
            jPanelWeeklyProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWeeklyProgramLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(22, 22, 22)
                .addComponent(jLabelPoolSize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel10)
                .addGap(3, 3, 3)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPoolSize1)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jTabbedPane2Tips.addTab("Weekly Program", jPanelWeeklyProgram);

        javax.swing.GroupLayout jPanelCalendarLayout = new javax.swing.GroupLayout(jPanelCalendar);
        jPanelCalendar.setLayout(jPanelCalendarLayout);
        jPanelCalendarLayout.setHorizontalGroup(
            jPanelCalendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 865, Short.MAX_VALUE)
        );
        jPanelCalendarLayout.setVerticalGroup(
            jPanelCalendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );

        jTabbedPane2Tips.addTab("Calendar(Soon)", jPanelCalendar);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swimming/panel.PNG"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Πανελλήνιος ");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Κολυμβητήριο Πεύκη");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swimming/pool-pefki.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(0, 26, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel3);

        javax.swing.GroupLayout jPanelGalleryLayout = new javax.swing.GroupLayout(jPanelGallery);
        jPanelGallery.setLayout(jPanelGalleryLayout);
        jPanelGalleryLayout.setHorizontalGroup(
            jPanelGalleryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGalleryLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 108, Short.MAX_VALUE))
        );
        jPanelGalleryLayout.setVerticalGroup(
            jPanelGalleryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
        );

        jTabbedPane2Tips.addTab("Gallery", jPanelGallery);

        jTabbedPanelProgram.addTab("Training Facilities", jTabbedPane2Tips);

        jLabelWarning.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelWarning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWarning.setText("You haven't made a program yet!");

        jLabelTrainProgram.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTrainProgram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swimming/trainprog SuperFinal.png"))); // NOI18N

        jLabelFinalButterflyMeters.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelFinalButterflyMeters.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFinalButterflyMeters.setText("?");
        jLabelFinalButterflyMeters.setEnabled(true);

        jLabelFinalBackstrokeMeters.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelFinalBackstrokeMeters.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFinalBackstrokeMeters.setText("?");
        jLabelFinalBackstrokeMeters.setEnabled(true);

        jLabelFinalBreakstrokeMeters.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelFinalBreakstrokeMeters.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFinalBreakstrokeMeters.setText("?");
        jLabelFinalBreakstrokeMeters.setEnabled(true);

        jLabelFinalFreestyleMeters.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelFinalFreestyleMeters.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFinalFreestyleMeters.setText("?");
        jLabelFinalFreestyleMeters.setEnabled(true);

        jButtonScreenShot.setText("Download");
        jButtonScreenShot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonScreenShotActionPerformed(evt);
            }
        });

        jLabelDateForProgram.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jFileChooser.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        jFileChooser.setDialogTitle("Save your program");
        jFileChooser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(jLabelDateForProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabelWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabelFinalButterflyMeters, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(704, 704, 704)
                .addComponent(jLabelFinalFreestyleMeters, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(jLabelFinalBackstrokeMeters, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(474, 474, 474)
                .addComponent(jLabelFinalBreakstrokeMeters, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabelTrainProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(376, 376, 376)
                .addComponent(jButtonScreenShot, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(125, Short.MAX_VALUE)
                    .addComponent(jFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(147, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jLabelFinalButterflyMeters, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabelFinalFreestyleMeters)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabelDateForProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabelWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabelFinalBackstrokeMeters))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabelFinalBreakstrokeMeters))
                    .addComponent(jLabelTrainProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonScreenShot)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(32, Short.MAX_VALUE)
                    .addComponent(jFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(32, Short.MAX_VALUE)))
        );

        jLabelTrainProgram.setVisible(false);

        jLabelFinalFreestyleMeters.setEnabled(true);
        jLabelFinalButterflyMeters.setVisible(false);
        jLabelFinalBackstrokeMeters.setVisible(false);
        jLabelFinalBreakstrokeMeters.setVisible(false);
        jLabelFinalFreestyleMeters.setVisible(false);
        jButtonScreenShot.setVisible(false);
        jFileChooser.setVisible(false);

        jTabbedPanelProgram.addTab("Program", jPanel4);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swimming/butterfly.png"))); // NOI18N
        jTabbedPane1.addTab("Butterfly", jLabel3);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swimming/backstroke.png"))); // NOI18N
        jTabbedPane1.addTab("Backstroke", jLabel5);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swimming/breakstroke.png"))); // NOI18N
        jTabbedPane1.addTab("Breaststroke", jLabel8);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swimming/freestyle.png"))); // NOI18N
        jTabbedPane1.addTab("Freestyle ", jLabel9);

        jTabbedPanelProgram.addTab("Tips - Strokes", jTabbedPane1);

        jTabbedPane2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel1.setLayout(null);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swimming/Records/Record25mBackStroke.png"))); // NOI18N
        jPanel1.add(jLabel20);
        jLabel20.setBounds(10, 0, 560, 210);

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(10, 222, 850, 10);

        jTabbedPane2.addTab("25m Pool Size", jPanel1);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swimming/Records/Record50mFreestyle.png"))); // NOI18N

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addGap(0, 222, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 250, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("50m Pool Size", jPanel2);

        jTabbedPanelProgram.addTab("Records (Soon)", jTabbedPane2);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setText("Version 1.01");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Προπονητής : Γιώργος Λεπίπας");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Αθλητής : Τάσος Λεπίπας (aka Michael Phelps)");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(jLabel15))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17)))
                .addContainerGap(361, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addGap(153, 153, 153)
                .addComponent(jLabel15)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        jTabbedPanelProgram.addTab("Information", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPanelProgram, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPanelProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 481, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFileChooserActionPerformed

    private void jButtonScreenShotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonScreenShotActionPerformed
        // TODO add your handling code here:

        //      jLabelTrainProgram.setVisible(false);
        //     jLabelFinalButterflyMeters.setVisible(false);
        //   jLabelFinalBackstrokeMeters.setVisible(false);
        //      jLabelFinalBreakstrokeMeters.setVisible(false);
        //      jLabelFinalFreestyleMeters.setVisible(false);
        //      jButtonScreenShot.setVisible(false);

        //      jFileChooser.setVisible(true);

        //  jFileChooser chooser = new jFileChooser();

        //  JFrame.setVisible(false);
        //      jTabbedPanelProgram.setVisible(true);

        //      int result = jFileChooser.showSaveDialog(jLabel1);
        //     int result = 0;
        //      FileChooseOptions(result);

        //        String snapshotLocation = "E:\\Users\\tasos\\Documents\\NetBeansProjects\\Michael Phelps\\dist";
        //
        CodeSource codeSource = Home.class.getProtectionDomain().getCodeSource();
        File jarFile;
        String jarDir;
        try {
            jarFile = new File(codeSource.getLocation().toURI().getPath());
            jarDir = jarFile.getParentFile().getPath();

        } catch (URISyntaxException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            jarDir = "";
        }

        BufferedImage bufImage = new BufferedImage(jTabbedPanelProgram.getSize().width, jTabbedPanelProgram.getSize().height - 70 , BufferedImage.TYPE_INT_BGR );
        jTabbedPanelProgram.paint(bufImage.createGraphics());

        DateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");
        Date date = new Date();

        File imageFile = new File(File.separator + jarDir + File.separator + "Πρόγραμμα - " + dateFormat.format(date) + ".jpeg");
        try{
            imageFile.createNewFile();
            ImageIO.write(bufImage, "jpeg", imageFile);
        }catch(Exception ex){
            System.err.println("Something went wrong");
        }
    }//GEN-LAST:event_jButtonScreenShotActionPerformed

    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
        // TODO add your handling code here:
        //  jTabbedPanelProgram.jLabelWarning.visibility
        jLabelWarning.setVisible(false);
        jLabelTrainProgram.setVisible(true);
        jButtonScreenShot.setVisible(true);
        jLabelFinalButterflyMeters.setVisible(true);
        jLabelFinalBackstrokeMeters.setVisible(true);
        jLabelFinalBreakstrokeMeters.setVisible(true);
        jLabelFinalFreestyleMeters.setVisible(true);
        if(textFieldButterfly.getText().isEmpty())
        jLabelFinalButterflyMeters.setText("0m");
        else
        jLabelFinalButterflyMeters.setText(textFieldButterfly.getText() + "m");

        if(textFieldBackstroke.getText().isEmpty())
        jLabelFinalBackstrokeMeters.setText("0m");
        else
        jLabelFinalBackstrokeMeters.setText(textFieldBackstroke.getText() + "m");

        if(textFieldBreakstroke.getText().isEmpty())
        jLabelFinalBreakstrokeMeters.setText("0m");
        else
        jLabelFinalBreakstrokeMeters.setText(textFieldBreakstroke.getText() + "m");

        if(textFieldFreestyle.getText().isEmpty())
        jLabelFinalFreestyleMeters.setText("0m");
        else
        jLabelFinalFreestyleMeters.setText(textFieldFreestyle.getText() + "m");

        DateFormat dateFormat = new SimpleDateFormat("HH:mm:ss dd/MM/yyyy ");
        Date date = new Date();
        jLabelDateForProgram.setText(dateFormat.format(date));
        //   jLabelDateForProgram.setText(jCalendar.getDate().toString());

    }//GEN-LAST:event_jButtonPrintActionPerformed

    private void textFieldFreestyleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldFreestyleKeyTyped
        // TODO add your handling code here:
        char vchar = evt.getKeyChar();
        if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE))
        evt.consume();
        if(textFieldFreestyle.getText().length()>= 4)
        evt.consume();
    }//GEN-LAST:event_textFieldFreestyleKeyTyped

    private void textFieldBreakstrokeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldBreakstrokeKeyTyped
        // TODO add your handling code here:
        char vchar = evt.getKeyChar();
        if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE))
        evt.consume();
        if(textFieldBreakstroke.getText().length()>= 4)
        evt.consume();
    }//GEN-LAST:event_textFieldBreakstrokeKeyTyped

    private void textFieldBackstrokeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldBackstrokeKeyTyped
        // TODO add your handling code here:
        char vchar = evt.getKeyChar();
        if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE))
        evt.consume();
        if(textFieldBackstroke.getText().length()>= 4)
        evt.consume();
    }//GEN-LAST:event_textFieldBackstrokeKeyTyped

    private void textFieldBackstrokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldBackstrokeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldBackstrokeActionPerformed

    private void textFieldButterflyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldButterflyKeyTyped
        // TODO add your handling code here:
        char vchar = evt.getKeyChar();
        if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE))
        evt.consume();
        if(textFieldButterfly.getText().length()>= 4)
        evt.consume();
    }//GEN-LAST:event_textFieldButterflyKeyTyped

    private void jButtonFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinishActionPerformed
        // TODO add your handling code here:
        jButtonDownload.setVisible(true);        
    }//GEN-LAST:event_jButtonFinishActionPerformed

    private void jButtonAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddNewActionPerformed
        // TODO add your handling code here:
           
        String text = jTextAreaProgram.getText();
        String style = jTextFieldSpecificStyle.getText();
        String meters = textFieldMeters.getText();

        jTextAreaProgram.setText(text + "\n" + "               " + meters + "m   ->" +  style );
        
        
        textFieldMeters.setText("");
        jTextFieldSpecificStyle.setText("");
        jTextAreaProgram.setVisible(true);
            
        
    }//GEN-LAST:event_jButtonAddNewActionPerformed

    private void textFieldButterflyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldButterflyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldButterflyActionPerformed

    private void textFieldMetersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldMetersActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_textFieldMetersActionPerformed

    private void textFieldMetersKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldMetersKeyTyped
        // TODO add your handling code here:
        
        char vchar = evt.getKeyChar();
         if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE))
         evt.consume();
         if(textFieldMeters.getText().length()>= 4)
         evt.consume();
         
    }//GEN-LAST:event_textFieldMetersKeyTyped

    private void jButtonDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDownloadActionPerformed
        // TODO add your handling code here:
        jLabelMeters.setVisible(false);
        jLabelStyle.setVisible(false);
        jTextFieldSpecificStyle.setVisible(false);
        textFieldMeters.setVisible(false);
        jButtonAddNew.setVisible(false);
        jButtonFinish.setVisible(false);
        jLabel19.setVisible(false);
        
        CodeSource codeSource = Home.class.getProtectionDomain().getCodeSource();
        File jarFile;
        String jarDir;
        try {
            jarFile = new File(codeSource.getLocation().toURI().getPath());
            jarDir = jarFile.getParentFile().getPath();

        } catch (URISyntaxException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            jarDir = "";
        }

        BufferedImage bufImage = new BufferedImage(jTabbedPanelProgram.getSize().width - 140, jTabbedPanelProgram.getSize().height - 22 , BufferedImage.TYPE_INT_BGR );
        jTabbedPanelProgram.paint(bufImage.createGraphics());

        DateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");
        Date date = new Date();

        File imageFile = new File(File.separator + jarDir + File.separator + "Πρόγραμμα - " + dateFormat.format(date) + ".jpeg");
        try{
            imageFile.createNewFile();
            ImageIO.write(bufImage, "jpeg", imageFile);
        }catch(Exception ex){
            System.err.println("Something went wrong");
        }
        
        jLabelMeters.setVisible(true);
        jLabelStyle.setVisible(true);
        jTextFieldSpecificStyle.setVisible(true);
        textFieldMeters.setVisible(true);
        jButtonAddNew.setVisible(true);
        jButtonFinish.setVisible(true);
        jLabel19.setVisible(true);
        
    }//GEN-LAST:event_jButtonDownloadActionPerformed

    
    private void FileChooseOptions(int result){
      //  jFileChooser = new JFileChooser();
      //  int result = jFileChooser.showOpenDialog(null);
        switch(result){
            case  JFileChooser.APPROVE_OPTION :
                
                String path = jFileChooser.getCurrentDirectory().toString();
                
                CodeSource codeSource = Home.class.getProtectionDomain().getCodeSource();
                File jarFile;
                String jarDir;
                try {
                    jarFile = new File(codeSource.getLocation().toURI().getPath());
                    jarDir = jarFile.getParentFile().getPath();
 
                } catch (URISyntaxException ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                    jarDir = "";
                }

                
                BufferedImage bufImage = new BufferedImage(jTabbedPanelProgram.getSize().width, jTabbedPanelProgram.getSize().height - 70 , BufferedImage.TYPE_INT_BGR );
                jTabbedPanelProgram.paint(bufImage.createGraphics());
                
                Graphics g = bufImage.getGraphics();
             //   g.dra
                
                DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                Date date = new Date();
                
                File imageFile = new File(File.separator + path + File.separator + "Πρόγραμμα - " + dateFormat.format(date) + ".jpeg");
                try{
                    imageFile.createNewFile();
                    ImageIO.write(bufImage, "jpeg", imageFile);
                }catch(IOException ex){
                    System.err.println("Something went wrong");
                }
                
                
                
                jLabelTrainProgram.setVisible(true);
                jFileChooser.setVisible(false);
                jButtonScreenShot.setVisible(true);
                jLabelFinalButterflyMeters.setVisible(true);
                jLabelFinalBackstrokeMeters.setVisible(true);
                jLabelFinalBreakstrokeMeters.setVisible(true);
                jLabelFinalFreestyleMeters.setVisible(true);

                break;
            case JFileChooser.CANCEL_OPTION :
                jLabelTrainProgram.setVisible(true);
                jFileChooser.setVisible(false);
                jButtonScreenShot.setVisible(true);
                jLabelFinalButterflyMeters.setVisible(true);
                jLabelFinalBackstrokeMeters.setVisible(true);
                jLabelFinalBreakstrokeMeters.setVisible(true);
                jLabelFinalFreestyleMeters.setVisible(true);
             //   jTabbedPanelProgram.setVisible(true);
                break;
            case JFileChooser.ERROR_OPTION:  
                jLabelTrainProgram.setVisible(true);
                jFileChooser.setVisible(false);
                jButtonScreenShot.setVisible(true);
                jLabelFinalButterflyMeters.setVisible(true);
                jLabelFinalBackstrokeMeters.setVisible(true);
                jLabelFinalBreakstrokeMeters.setVisible(true);
                jLabelFinalFreestyleMeters.setVisible(true);
             //   jTabbedPanelProgram.setVisible(true);
                break;
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddNew;
    private javax.swing.JButton jButtonDownload;
    private javax.swing.JButton jButtonFinish;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JButton jButtonScreenShot;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBackstroke;
    private javax.swing.JLabel jLabelBreaststroke;
    private javax.swing.JLabel jLabelButterfly;
    private javax.swing.JLabel jLabelDateForProgram;
    private javax.swing.JLabel jLabelFinalBackstrokeMeters;
    private javax.swing.JLabel jLabelFinalBreakstrokeMeters;
    private javax.swing.JLabel jLabelFinalButterflyMeters;
    private javax.swing.JLabel jLabelFinalFreestyleMeters;
    private javax.swing.JLabel jLabelFreestyle;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelMeters;
    private javax.swing.JLabel jLabelPoolSize;
    private javax.swing.JLabel jLabelPoolSize1;
    private javax.swing.JLabel jLabelStyle;
    private static javax.swing.JLabel jLabelTrainProgram;
    private static javax.swing.JLabel jLabelWarning;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelCalendar;
    private javax.swing.JPanel jPanelGallery;
    private javax.swing.JPanel jPanelHome_New;
    private javax.swing.JPanel jPanelHome_Old;
    private javax.swing.JPanel jPanelWeeklyProgram;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane2Tips;
    private javax.swing.JTabbedPane jTabbedPanelProgram;
    private javax.swing.JTextArea jTextAreaProgram;
    private javax.swing.JTextField jTextFieldSpecificStyle;
    private java.awt.TextField textFieldBackstroke;
    private java.awt.TextField textFieldBreakstroke;
    private java.awt.TextField textFieldButterfly;
    private java.awt.TextField textFieldFreestyle;
    private java.awt.TextField textFieldMeters;
    // End of variables declaration//GEN-END:variables
}
